### ISSUE TITLE
Ability to control the IR ring around the camera.

### ISSUE THREAD

**Issue by Alfred-AdMobilize** [matrix-io/matrix-creator-hal#40]

**Comment by nmaster** [comment]
I see a couple of reasons for that improvement:

- if operated on battery power, always-on IR LEDs introduce an uncontrollable source of drain.
- longer exposure to IR light can be harmful to the human retina, depending on its power. Health risk!

Would be great to have some abstraction (e.g. in HAL or even higher abstraction layers you guys do) instead of having to program the FPGA directly.

Thanks!

**Comment by kdpatino** [comment]
@nmaster 
Thank You for your feedback. We can  add this for sure. I will post here when we complete this implementation.

Regards,

Kevin

**Comment by nmaster** [comment]
Found a hint here: https://github.com/matrix-io/matrix-creator-fpga/blob/8e29c4daffa7942cfcf9f8be17301a37c5935b0a/creator_core/creator.ucf#L50

Seems like RPI GPIO pin 5 is wired to the IR LED ring. Used wiringpi to successfully validate this idea.

`gpio -g write 5 0` - disable IR ring
`gpio -g write 5 1` - enable IR ring

Thus, it seems low-hanging fruit to add an API method for that in HAL, simply using the GPIO abstraction. Go for it, guys! ;)

**Comment by kdpatino** [comment]
Hello @nmaster 

In the last release, we connected the IR-RING and IR TX to the GPIO13 and the IR-RX to GPIO16

![screenshot from 2018-03-28 09-51-42](https://user-images.githubusercontent.com/17411203/38037080-baa77940-326d-11e8-9936-ab898978a3b8.png)

You could control it with:
```
echo 13 > /sys/class/gpio/export 2> /dev/null
echo out > /sys/class/gpio/gpio13/direction
echo 1 > /sys/class/gpio/gpio13/value
echo 0 > /sys/class/gpio/gpio13/value
```

Or use it with the wiringPi libraries.

Regards, 

Kevin Patino
